version: "3"

services:
#  dict_center:
#    build: dict_center
#    command: go build && ./KW
#    ports:
#     - "8080:8081"
#    volumes:
#     - /go/bin:/code
#    links:
#     - redis
#     - mongo
#    environment:
#     - REDIS_PORT_6379_TCP_ADDR=localhost
#     - REDIS_PORT_6379_TCP_PORT=6379
#     - MONGO_PORT_6379_TCP_ADDR=localhost
#     - MONGO_PORT_6379_TCP_PORT=6379
#    image: dev:1.8
  db-1:
    container_name: mongodb-1
    image: mongo:3.4
    command: --replSet "rs0"
    ports:
      - "27017:27017"
    hostname: master.mongors
    extra_hosts:
     - "master.mongors:172.16.238.10"
     - "slave1.mongors:172.16.238.11"
     - "slave2.mongors:172.16.238.12"
    networks:
      mongo_rs_net:
        ipv4_address: 172.16.238.10
  db-2:
    container_name: mongodb-2
    image: mongo:3.4
    command: --replSet "rs0"
    hostname: slave1.mongors
    ports:
      - "27018:27017"
    extra_hosts:
     - "master.mongors:172.16.238.10"
     - "slave1.mongors:172.16.238.11"
     - "slave2.mongors:172.16.238.12"
    networks:
      mongo_rs_net:
        ipv4_address: 172.16.238.11
  db-3:
    container_name: mongodb-3
    image: mongo:3.4
    command: --replSet "rs0"
    hostname: slave2.mongors
    ports:
      - "27019:27017"
    extra_hosts:
     - "master.mongors:172.16.238.10"
     - "slave1.mongors:172.16.238.11"
     - "slave2.mongors:172.16.238.12"
    networks:
      mongo_rs_net:
        ipv4_address: 172.16.238.12
#  redis:
#    image: redis:3.2
#    ports:
#      - "6379:6379"

networks:
  mongo_rs_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
